spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/openteams
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      base-path: /actuator
      discovery:
        enabled: false
      exposure:
        include: info,health,metrics
      cors:
        allowed-methods: GET

server:
  port: 8080
  error:
    whitelabel:
      enabled: true
